<?xml version="1.0" encoding="utf-8"?>
<StyledLayerDescriptor xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd">
<!--Generated by GeoCat Bridge for QGIS 4.4 (based on bridgestyle 0.1)-->
<NamedLayer>
<Name>view_eez_intersections</Name>
<UserStyle>
<Title>view_eez_intersections</Title>
<FeatureTypeStyle>
<Rule>
<Name>8 - 30.8</Name>
<ogc:Filter>
<ogc:And>
<ogc:PropertyIsGreaterThanOrEqualTo>
<ogc:PropertyName>intersection_count</ogc:PropertyName>
<ogc:Literal>8.0</ogc:Literal>
</ogc:PropertyIsGreaterThanOrEqualTo>
<ogc:PropertyIsLessThanOrEqualTo>
<ogc:PropertyName>intersection_count</ogc:PropertyName>
<ogc:Literal>30.8</ogc:Literal>
</ogc:PropertyIsLessThanOrEqualTo>
</ogc:And>
</ogc:Filter>
<MinScaleDenominator>10000000.0</MinScaleDenominator>
<MaxScaleDenominator>100000000.0</MaxScaleDenominator>
<PolygonSymbolizer>
<Fill>
<CssParameter name="fill">#ffffff</CssParameter>
<CssParameter name="fill-opacity">1.0</CssParameter>
</Fill>
<Stroke>
<CssParameter name="stroke">#232323</CssParameter>
<CssParameter name="stroke-width">0.9285714285714285</CssParameter>
<CssParameter name="stroke-opacity">1.0</CssParameter>
</Stroke>
</PolygonSymbolizer>
</Rule>
<Rule>
<Name>30.8 - 39.8</Name>
<ogc:Filter>
<ogc:And>
<ogc:PropertyIsGreaterThan>
<ogc:PropertyName>intersection_count</ogc:PropertyName>
<ogc:Literal>30.8</ogc:Literal>
</ogc:PropertyIsGreaterThan>
<ogc:PropertyIsLessThanOrEqualTo>
<ogc:PropertyName>intersection_count</ogc:PropertyName>
<ogc:Literal>39.8</ogc:Literal>
</ogc:PropertyIsLessThanOrEqualTo>
</ogc:And>
</ogc:Filter>
<MinScaleDenominator>10000000.0</MinScaleDenominator>
<MaxScaleDenominator>100000000.0</MaxScaleDenominator>
<PolygonSymbolizer>
<Fill>
<CssParameter name="fill">#ffbfbf</CssParameter>
<CssParameter name="fill-opacity">1.0</CssParameter>
</Fill>
<Stroke>
<CssParameter name="stroke">#232323</CssParameter>
<CssParameter name="stroke-width">0.9285714285714285</CssParameter>
<CssParameter name="stroke-opacity">1.0</CssParameter>
</Stroke>
</PolygonSymbolizer>
</Rule>
<Rule>
<Name>39.8 - 48.8</Name>
<ogc:Filter>
<ogc:And>
<ogc:PropertyIsGreaterThan>
<ogc:PropertyName>intersection_count</ogc:PropertyName>
<ogc:Literal>39.8</ogc:Literal>
</ogc:PropertyIsGreaterThan>
<ogc:PropertyIsLessThanOrEqualTo>
<ogc:PropertyName>intersection_count</ogc:PropertyName>
<ogc:Literal>48.8</ogc:Literal>
</ogc:PropertyIsLessThanOrEqualTo>
</ogc:And>
</ogc:Filter>
<MinScaleDenominator>10000000.0</MinScaleDenominator>
<MaxScaleDenominator>100000000.0</MaxScaleDenominator>
<PolygonSymbolizer>
<Fill>
<CssParameter name="fill">#ff8080</CssParameter>
<CssParameter name="fill-opacity">1.0</CssParameter>
</Fill>
<Stroke>
<CssParameter name="stroke">#232323</CssParameter>
<CssParameter name="stroke-width">0.9285714285714285</CssParameter>
<CssParameter name="stroke-opacity">1.0</CssParameter>
</Stroke>
</PolygonSymbolizer>
</Rule>
<Rule>
<Name>48.8 - 77.2</Name>
<ogc:Filter>
<ogc:And>
<ogc:PropertyIsGreaterThan>
<ogc:PropertyName>intersection_count</ogc:PropertyName>
<ogc:Literal>48.8</ogc:Literal>
</ogc:PropertyIsGreaterThan>
<ogc:PropertyIsLessThanOrEqualTo>
<ogc:PropertyName>intersection_count</ogc:PropertyName>
<ogc:Literal>77.2</ogc:Literal>
</ogc:PropertyIsLessThanOrEqualTo>
</ogc:And>
</ogc:Filter>
<MinScaleDenominator>10000000.0</MinScaleDenominator>
<MaxScaleDenominator>100000000.0</MaxScaleDenominator>
<PolygonSymbolizer>
<Fill>
<CssParameter name="fill">#ff4040</CssParameter>
<CssParameter name="fill-opacity">1.0</CssParameter>
</Fill>
<Stroke>
<CssParameter name="stroke">#232323</CssParameter>
<CssParameter name="stroke-width">0.9285714285714285</CssParameter>
<CssParameter name="stroke-opacity">1.0</CssParameter>
</Stroke>
</PolygonSymbolizer>
</Rule>
<Rule>
<Name>77.2 - 91</Name>
<ogc:Filter>
<ogc:And>
<ogc:PropertyIsGreaterThan>
<ogc:PropertyName>intersection_count</ogc:PropertyName>
<ogc:Literal>77.2</ogc:Literal>
</ogc:PropertyIsGreaterThan>
<ogc:PropertyIsLessThanOrEqualTo>
<ogc:PropertyName>intersection_count</ogc:PropertyName>
<ogc:Literal>91.0</ogc:Literal>
</ogc:PropertyIsLessThanOrEqualTo>
</ogc:And>
</ogc:Filter>
<MinScaleDenominator>10000000.0</MinScaleDenominator>
<MaxScaleDenominator>100000000.0</MaxScaleDenominator>
<PolygonSymbolizer>
<Fill>
<CssParameter name="fill">#ff0000</CssParameter>
<CssParameter name="fill-opacity">1.0</CssParameter>
</Fill>
<Stroke>
<CssParameter name="stroke">#232323</CssParameter>
<CssParameter name="stroke-width">0.9285714285714285</CssParameter>
<CssParameter name="stroke-opacity">1.0</CssParameter>
</Stroke>
</PolygonSymbolizer>
</Rule>
<Rule>
<Name>labeling</Name>
<TextSymbolizer>
<Label>
<ogc:PropertyName>intersection_count</ogc:PropertyName>
</Label>
<Font>
<CssParameter name="font-family">Open Sans</CssParameter>
<CssParameter name="font-size">12.607142857142854</CssParameter>
</Font>
<LabelPlacement>
<PointPlacement>
<AnchorPoint>
<AnchorPointX>0.5</AnchorPointX>
<AnchorPointY>0.5</AnchorPointY>
</AnchorPoint>
<Displacement>
<DisplacementX>0.0</DisplacementX>
<DisplacementY>0.0</DisplacementY>
</Displacement>
<Rotation>0.0</Rotation>
</PointPlacement>
</LabelPlacement>
<Fill>
<CssParameter name="fill">#323232</CssParameter>
</Fill>
<VendorOption name="autoWrap">50</VendorOption>
<VendorOption name="group">yes</VendorOption>
</TextSymbolizer>
</Rule>
</FeatureTypeStyle>
</UserStyle>
</NamedLayer>
</StyledLayerDescriptor>
